#!/usr/bin/bash
#set -x

adb="/home/vmm/dev/opt/android-sdk-linux/platform-tools/adb"


adb_check() {
  for i in `seq 1 10`
  do
    $adb devices 2>/dev/null | grep device$ >/dev/null && return 0
    echo -n "."
    sleep 1
  done
  return 1
}

rndis_check() {
  if $adb shell getprop sys.usb.config | grep rndis >/dev/null
  then
    return 0
  else
    return 1
  fi
}

tether_toggle() {
  # go home
  $adb shell input keyevent 3

  # open tethering settings
  $adb shell am start -a android.intent.action.MAIN -n com.android.settings/.TetherSettings

  # wait 1 second to start activity
  sleep 1

  # move up - this always select first list item
  $adb shell input keyevent 19

  # move down - select "USB tethering"
  $adb shell input keyevent 20

  # toggle checkbox
  $adb shell input keyevent 66

  # alternatively, tap checkbox
  #$adb shell input tap 400 300

  # adb shell is unavailable for ~3 secs
  sleep 5

  # return home
  $adb shell input keyevent 3

  # turn off the screen
  $adb shell input keyevent 26
}

wifi_enable() {
  $adb shell svc wifi enable
}

wifi_disable() {
  $adb shell svc wifi disable
}

error() {
  echo $@
  exit 1
}


if ! adb_check
then
  error "No android devices found, exiting.."
fi

wifi_enable

if ! rndis_check
then
  echo "RNDIS not enabled, running tethering.."
  tether_toggle
else
  echo "RNDIS already enabled"
fi

if ! rndis_check
then
  err "Failed to start USB tethering"
fi
