#!/usr/bin/env bash

# Set path to adb binary
adb="/opt/android-sdk/platform-tools/adb"

echo "Enable Wi-Fi"
$adb shell svc wifi enable

#echo "Set MAC address for RNDIS interface"
#$adb shell 'echo "AA:BB:CC:DD:EE:FF" > /sys/class/android_usb/f_rndis/ethaddr'

echo "Enable USB tethering"
$adb shell setprop persist.sys.usb.config rndis,adb

# Device is unavailable for 1 sec.
sleep 2

echo "Set iptables rules"
# Got these strings from classes.dex inside tethering apk
$adb shell iptables -A POSTROUTING -s 192.168.42.0/24 -j MASQUERADE -t nat
$adb shell iptables -A FORWARD -j ACCEPT -i wlan0  -o rndis0
$adb shell iptables -A FORWARD -j ACCEPT -i ccmni0 -o rndis0
$adb shell iptables -A FORWARD -j ACCEPT -i ccmni1 -o rndis0
$adb shell iptables -A FORWARD -j ACCEPT -i ccmni2 -o rndis0
$adb shell iptables -A FORWARD -j ACCEPT -i rndis0 -o wlan0
$adb shell iptables -A FORWARD -j ACCEPT -i rndis0 -o ccmni0
$adb shell iptables -A FORWARD -j ACCEPT -i rndis0 -o ccmni1
$adb shell iptables -A FORWARD -j ACCEPT -i rndis0 -o ccmni2

echo "Configure RNDIS interface"
$adb shell ip addr add 192.168.42.129/24 dev rndis0
$adb shell ip link set rndis0 up

echo "Apply iptables rules"
$adb shell iptables -P FORWARD ACCEPT

echo "Enable IP forwarding"
$adb shell 'echo 1 > /proc/sys/net/ipv4/ip_forward'


# cannot run net phase without root capabilities
[[ $EUID -eq 0 ]] || exit

echo "Set up network interface"

sudo ip route del default 2>/dev/null || true
sudo ip route flush dev usb0
sudo ip addr flush dev usb0
sudo ip addr add 192.168.42.130/24 dev usb0
sudo ip link set usb0 up
sudo ip route add default via 192.168.42.129 dev usb0

# DNS should be pre-configured
